---
version: "2.1"
services:
  wireguard:
    image: weejewel/wg-easy:5
    container_name: wg-easy
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WG_HOST=127.0.0.1
      - PASSWORD=mKbU8FrQActcLqBZ
    volumes:
      - ./.wg-easy:/etc/wireguard
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
